import {
  orderConfirmationEmail,
  voucherEmail,
  volSurMesureQuoteEmail,
  reservationConfirmationFreeEmail,
  reservationPaymentConfirmationEmail,
  volSurMesureAcompteEmail,
  reservationDateConfirmeeEmail,
  reservationHeureConfirmeeEmail,
  reservationReportConfirmeeEmail,
  contactNotificationEmail,
  contactAcknowledgmentEmail,
  contactReplyEmail,
  reservationPaymentInvitationEmail,
  reservationPaymentReminderEmail,
  reservationAutoAnnuleeEmail,
  flightReminderEmail,
  postVolEmail,
  satisfactionResultEmail,
  customEmail,
  routeFeedbackAdminEmail,
  rescheduleInviteEmail,
  rescheduleConfirmationEmail,
  routeProposalEmail,
  paymentLinkEmail,
  newsletterFromBlocksEmail,
  newsletterConfirmationEmail,
  newsletterCampaignEmail,
  type EmailPriceBreakdown,
} from "@/lib/email-templates";
import { EmailsPreviewClient, type EmailPreviewEntry } from "@/components/admin/EmailsPreviewClient";

export const metadata = { title: "Emails · Admin" };

// Données d'exemple, réalistes mais fictives — pour visualiser les gabarits réels
// de lib/email-templates.ts sans dépendre de données en base.

const breakdownExample: EmailPriceBreakdown = {
  coutVol: 180,
  dureeMin: 60,
  distKm: 220,
  provisionMarge: 20,
  taxesEscales: 0,
  voucherDiscount: 0,
  couponDiscount: 10,
  couponCode: "WELCOME2026",
  total: 190,
};

export default function EmailsPreviewPage() {
  const entries: EmailPreviewEntry[] = [
    {
      id: "order-confirmation",
      category: "Boutique",
      label: "Commande reçue",
      html: orderConfirmationEmail({
        orderRef: "FH-2026-0184",
        customerEmail: "sophie.martin@example.com",
        customerName: "Sophie Martin",
        items: [{ title: "Casquette Fly Horizons", quantity: 1, unit_price: 24.9 }],
        subtotal: 24.9,
        shippingCost: 4.9,
        discountAmount: 0,
        total: 29.8,
        shippingAddress: {
          full_name: "Sophie Martin",
          line1: "Rue de la Station 12",
          city: "Namur",
          postal_code: "5000",
          country: "Belgique",
        },
        orderDate: new Date().toISOString(),
      }),
    },
    {
      id: "voucher-single",
      category: "Boutique",
      label: "Envoi d'un bon de vol",
      html: voucherEmail({
        orderRef: "FH-2026-0185",
        customerName: "Laurent Dubois",
        codes: [{ code: "AB12-CD34-EF56-GH78", duration_minutes: 60, product_title: "Vol partagé 60 min" }],
      }),
    },
    {
      id: "reservation-free",
      category: "Réservation standard",
      label: "Réservation confirmée · voucher",
      html: reservationConfirmationFreeEmail({
        prenom: "Camille",
        nom: "Petit",
        dateStr: "samedi 15 août 2026",
        heure: "14:00",
        duree: 60,
        passengers: 2,
        voucherCode: "AB12-CD34-EF56-GH78",
        reservationId: "sample-id",
      }),
    },
    {
      id: "reservation-paid",
      category: "Réservation standard",
      label: "Réservation confirmée · paiement reçu",
      html: reservationPaymentConfirmationEmail({
        prenom: "Camille",
        nom: "Petit",
        dateStr: "samedi 15 août 2026",
        heure: "14:00",
        duree: 60,
        passengers: 2,
        montantPaye: 190,
        reservationId: "sample-id",
      }),
    },
    {
      id: "payment-invitation",
      category: "Réservation standard",
      label: "Invitation au paiement",
      html: reservationPaymentInvitationEmail({
        prenom: "Camille",
        nom: "Petit",
        dateStr: "samedi 15 août 2026",
        heure: "14:00",
        duree: 60,
        montant: 190,
        paymentUrl: "https://fly-horizons.com/reservation/pay/exemple",
        breakdown: breakdownExample,
      }),
    },
    {
      id: "payment-reminder",
      category: "Rappels & annulation",
      label: "Rappel de paiement · T-72h",
      html: reservationPaymentReminderEmail({
        prenom: "Camille",
        nom: "Petit",
        dateStr: "samedi 15 août 2026",
        heure: "14:00",
        duree: 60,
        montant: 190,
        paymentUrl: "https://fly-horizons.com/reservation/pay/exemple",
        deadlineStr: "jeudi 13 août à 14:00",
        breakdown: breakdownExample,
      }),
    },
    {
      id: "auto-annulee",
      category: "Rappels & annulation",
      label: "Annulation automatique",
      html: reservationAutoAnnuleeEmail({
        prenom: "Camille",
        nom: "Petit",
        dateStr: "samedi 15 août 2026",
        heure: "14:00",
        duree: 60,
        bookingUrl: "https://fly-horizons.com/nos-offres",
        source: "auto",
      }),
    },
    {
      id: "flight-reminder",
      category: "Rappels & annulation",
      label: "Rappel J-2 avant le vol",
      html: flightReminderEmail({
        prenom: "Camille",
        dateStr: "samedi 15 août 2026",
        heure: "14:00",
        duree: 60,
        type_resa: "standard",
        accountUrl: "https://fly-horizons.com/account/reservations/exemple",
        dateISO: "2026-08-15",
      }),
    },
    {
      id: "reschedule-invite",
      category: "Rappels & annulation",
      label: "Invitation à reporter (météo)",
      html: rescheduleInviteEmail({
        prenom: "Camille",
        dateStr: "samedi 15 août 2026",
        duree: 60,
        rescheduleUrl: "https://fly-horizons.com/reservation/reporter/exemple",
      }),
    },
    {
      id: "reschedule-confirmation",
      category: "Rappels & annulation",
      label: "Confirmation de report",
      html: rescheduleConfirmationEmail({
        prenom: "Camille",
        oldDateStr: "samedi 15 août 2026",
        newDateStr: "samedi 22 août 2026",
        duree: 60,
        accountUrl: "https://fly-horizons.com/account/reservations/exemple",
      }),
    },
    {
      id: "report-confirmee",
      category: "Rappels & annulation",
      label: "Nouvelle date confirmée · après un report",
      html: reservationReportConfirmeeEmail({
        prenom: "Camille",
        dateStr: "samedi 22 août 2026",
        heure: "14:00",
        duree: 60,
        dateISO: "2026-08-22",
      }),
    },
    {
      id: "date-confirmee",
      category: "Vol sur mesure",
      label: "Date de vol confirmée (admin)",
      html: reservationDateConfirmeeEmail({
        prenom: "Camille",
        dateStr: "samedi 15 août 2026",
        duree: 60,
      }),
    },
    {
      id: "heure-confirmee",
      category: "Vol sur mesure",
      label: "Créneau horaire confirmé (admin)",
      html: reservationHeureConfirmeeEmail({
        prenom: "Camille",
        dateStr: "samedi 15 août 2026",
        heure: "14:00",
        duree: 60,
        dateISO: "2026-08-15",
      }),
    },
    {
      id: "vol-mesure-quote",
      category: "Vol sur mesure",
      label: "Demande de vol sur mesure",
      html: volSurMesureQuoteEmail({
        prenom: "Julien",
        nom: "Renard",
        date: "2026-08-20",
        heure: "10:00",
        dureeMin: 75,
        distKm: 260,
        styleVol: "Panoramique, châteaux",
        stopovers: [],
        prixEstime: 225,
        discount: 0,
        prixBillable: 225,
        acompte: 25,
        taxesEscales: 0,
        totalAcompte: 250,
        voucherCode: null,
      }),
    },
    {
      id: "vol-mesure-acompte",
      category: "Vol sur mesure",
      label: "Provision reçue · vol sur mesure",
      html: volSurMesureAcompteEmail({
        prenom: "Julien",
        nom: "Renard",
        dateStr: "jeudi 20 août 2026",
        heure: "10:00",
        dureeEstimee: 75,
        montantPaye: 250,
        breakdown: breakdownExample,
      }),
    },
    {
      id: "route-proposal",
      category: "Vol sur mesure",
      label: "Proposition d'itinéraire",
      html: routeProposalEmail({
        prenom: "Julien",
        dateStr: "jeudi 20 août 2026",
        waypoints: [{ nom: "Château de Freÿr" }, { nom: "Citadelle de Namur" }],
        adminComment: "Voici le tracé que je propose, en fonction de la météo annoncée et des zones survolables ce jour-là.",
        responseUrl: "https://fly-horizons.com/vol/proposition/exemple",
        totalAcompte: 250,
        alreadyPaid: false,
      }),
    },
    {
      id: "payment-link",
      category: "Vol sur mesure",
      label: "Lien de paiement après itinéraire",
      html: paymentLinkEmail({
        prenom: "Julien",
        dateStr: "jeudi 20 août 2026",
        duree: 75,
        acompte: 250,
        paymentUrl: "https://fly-horizons.com/vol-sur-mesure/pay/exemple",
        breakdown: breakdownExample,
      }),
    },
    {
      id: "route-feedback-admin",
      category: "Vol sur mesure",
      label: "Retour client sur itinéraire (admin)",
      html: routeFeedbackAdminEmail({
        clientPrenom: "Julien",
        clientNom: "Renard",
        clientEmail: "julien.renard@example.com",
        resaId: "sample-id",
        dateStr: "jeudi 20 août 2026",
        type: "validated",
        adminUrl: "https://fly-horizons.com/admin/vols",
      }),
    },
    {
      id: "contact-notification",
      category: "Contact",
      label: "Nouveau message (admin)",
      html: contactNotificationEmail({
        nom: "Élise Dupont",
        email: "elise.dupont@example.com",
        sujet: "Question sur la réservation",
        message: "Bonjour, est-il possible de venir à 4 personnes pour un vol de 60 minutes ?",
      }),
    },
    {
      id: "contact-ack",
      category: "Contact",
      label: "Accusé de réception client",
      html: contactAcknowledgmentEmail({
        nom: "Élise Dupont",
        email: "elise.dupont@example.com",
        sujet: "Question sur la réservation",
        message: "Bonjour, est-il possible de venir à 4 personnes pour un vol de 60 minutes ?",
        threadUrl: "https://fly-horizons.com/contact/ticket/exemple",
      }),
    },
    {
      id: "contact-reply",
      category: "Contact",
      label: "Réponse admin",
      html: contactReplyEmail({
        nom: "Élise Dupont",
        email: "elise.dupont@example.com",
        sujet: "Question sur la réservation",
        reponse: "Bonjour Élise, l'avion accueille jusqu'à 3 passagers maximum, pilote compris. Je reste disponible si vous avez d'autres questions !",
        threadUrl: "https://fly-horizons.com/contact/ticket/exemple",
      }),
    },
    {
      id: "post-vol",
      category: "Post-vol",
      label: "Remerciement + enquête",
      html: postVolEmail({
        prenom: "Camille",
        dateStr: "samedi 15 août 2026",
        duree: 60,
        surveyUrl: "https://fly-horizons.com/satisfaction/exemple",
      }),
    },
    {
      id: "satisfaction-result",
      category: "Post-vol",
      label: "Résultat enquête (admin)",
      html: satisfactionResultEmail({
        prenom: "Camille",
        nom: "Petit",
        dateStr: "samedi 15 août 2026",
        duree: 60,
        noteGlobale: 5,
        noteAccueil: 5,
        notePilote: 5,
        commentaire: "Expérience incroyable, Romain a été très pédagogue et rassurant du début à la fin !",
        nbPhotos: 3,
      }),
    },
    {
      id: "custom-email",
      category: "Divers",
      label: "Email libre stylisé",
      html: customEmail({
        subject: "Un mot de Romain",
        body: "Bonjour,\n\nJe voulais juste vous confirmer que tout est en ordre pour votre vol.\n\nÀ bientôt !",
      }),
    },
    {
      id: "newsletter-confirmation",
      category: "Newsletter",
      label: "Confirmation d'inscription",
      html: newsletterConfirmationEmail("Camille", "https://fly-horizons.com/newsletter/unsubscribe?token=exemple"),
    },
    {
      id: "newsletter-campaign",
      category: "Newsletter",
      label: "Campagne (texte libre)",
      html: newsletterCampaignEmail(
        "Un vol est organisé ce week-end !",
        "Bonjour,\n\nJ'organise un vol partagé ce samedi en fin de matinée, il reste de la place à bord.\n\nSi ça vous dit de nous rejoindre, répondez à cet email ou réservez directement sur le site.",
        "Camille",
        "https://fly-horizons.com/newsletter/unsubscribe?token=exemple"
      ),
    },
    {
      id: "newsletter-blocks",
      category: "Newsletter",
      label: "Campagne (éditeur de blocs)",
      html: newsletterFromBlocksEmail(
        "Un vol est organisé ce week-end !",
        [
          { id: "1", type: "heading", level: 1, text: "Une place se libère ce samedi" },
          { id: "2", type: "text", content: "J'organise un vol partagé ce samedi en fin de matinée, au départ de Charleroi. Il reste de la place à bord si l'un d'entre vous souhaite se joindre." },
          { id: "3", type: "button", text: "Voir les vols disponibles", url: "https://fly-horizons.com/nos-offres" },
        ],
        "Camille",
        "https://fly-horizons.com/newsletter/unsubscribe?token=exemple"
      ),
    },
  ];

  return <EmailsPreviewClient entries={entries} />;
}
